export const songs = [
  {
    movie: "Yaraana",
    name: "Mera Piya Ghar Aaya",
    youtubeId: "xVViRaALOLM",
    // startTime: "0",
  },
  {
    movie: "Partner",
    name: "Soni De Nakhre",
    youtubeId: "GFljvZMZI0U",
    // startTime: "0",
  },
  {
    movie: "Tashan",
    name: "Falak Tak",
    youtubeId: "vr8RaNuWjWc",
    // startTime: "0",
  },
  {
    movie: "Dilwale Dulhania Le Jayenge",
    name: "Ruk Ja O Dil Deewane",
    youtubeId: "jBpRItrod-Q",
    // startTime: "0",
  },
  {
    movie: "Bachna Ae Haseeno",
    name: "Jogi Mahi",
    youtubeId: "GKyMgyNsRKI",
    // startTime: "0",
  },
  {
    movie: "Hum Aapke Hain Koun",
    name: "Didi Tera Devar Deewana",
    youtubeId: "2V56f0xZNqw",
    // startTime: "0",
  },
  {
    movie: "Om Shanti Om",
    name: "Deewangi Deewangi",
    youtubeId: "VzLG6OqOcn8",
    // startTime: "0",
  },
  {
    movie: "Rab Ne Bana Di Jodi",
    name: "Tujh Mein Rab Dikta Hain",
    youtubeId: "qoq8B8ThgEM",
    // startTime: "0",
  },
  {
    movie: "Brahmastra",
    name: "Kesariya",
    youtubeId: "BddP6PYo2gs",
    // startTime: "0",
  },
  {
    movie: "Judwaa 2 ",
    name: "Chalti Hai Kya 9 Se 12",
    youtubeId: "E9OFaR2DSOI",
    // startTime: "0",
  },
  {
    movie: "Dil Dhadakne Do",
    name: "Gallan Goodiyaan",
    youtubeId: "jCEdTq3j-0U",
    // startTime: "0",
  },
  {
    movie: "Band Baaja Baaraat",
    name: "Ainvayi Ainvayi",
    youtubeId: "pElk1ShPrcE",
    // startTime: "0",
  },
  {
    movie: "Fan",
    name: "Jabra Fan",
    youtubeId: "d4_szl5EEww",
    // startTime: "0",
  },
  {
    movie: "Befikre",
    name: "Nashe Si Chadh Gayi",
    youtubeId: "Wd2B8OAotU8",
    // startTime: "0",
  },
  {
    movie: "Gunday",
    name: "Tune Maari Entriyaan",
    youtubeId: "-8SlOkUAW-4",
    // startTime: "0",
  },
  {
    movie: "Dabangg 2",
    name: "Fevicol Se",
    youtubeId: "zE7Pwgl6sLA",
    // startTime: "0",
  },
  {
    movie: "Ra.One",
    name: "Chammak Challo",
    youtubeId: "lxB-ki-qE64",
    // startTime: "0",
  },
  {
    movie: "Singh Is Kinng",
    name: "Jee Karda",
    youtubeId: "40IlftR0R_U",
    // startTime: "0",
  },
  {
    movie: "Baar Baar Dekho",
    name: "Kala Chashma",
    youtubeId: "k4yXQkG2s1E",
    // startTime: "0",
  },
  {
    movie: "Aarzoo",
    name: "Sajan Sajan Teri Dulhan",
    youtubeId: "vvvDkFN9LUU",
  },
  {
    movie: "Mere Brother Ki Dulhan",
    name: "Do Dhaari Talwaar",
    youtubeId: "m66aEQ3Ssdw",
  },
  {
    movie: "Shamshera",
    name: "Kaale Naina",
    youtubeId: "Ieh-dXsR0OE",
  },
  {
    movie: "Kalank",
    name: "Ghar More Pardesiya",
    youtubeId: "pp8vAFFc5E0",
  },
  {
    movie: "Guru",
    name: "Barso Re",
    youtubeId: "xj_OHHWcPNw",
  },
  {
    movie: "Veer-Zaara",
    name: "Hum To Bhai Jaise Hain",
    youtubeId: "c_L5nSf91zs",
  },
  {
    movie: "Welcome Back",
    name: "Tutti Bole Wedding Di",
    youtubeId: "r2LwEwLiRhc",
  },
  {
    movie: "Housefull 2",
    name: "Right Now Now",
    youtubeId: "m_4lF320DfQ",
  },
  {
    movie: "Dostana",
    name: "Maa Da Laadla",
    youtubeId: "wVCZmXiK-6k",
  },
  {
    movie: "Singh Is Bliing",
    name: "Dil Kare Chu Che",
    youtubeId: "4Lzih-SfYDM",
  },
  {
    movie: "Hum Aapke Hain Koun",
    name: "Maye Ni Maye",
    youtubeId: "Ua5AW2czRAE",
  },
  {
    movie: "Vivah",
    name: "Milan Abhi Aadha Adhura Hai",
    youtubeId: "bv5j1CUTVGM",
  },
  {
    movie: "Fanaa",
    name: "Des Rangila",
    youtubeId: "drlfr5Rtb1o",
  },
  {
    movie: "Kesari",
    name: "Teri Mitti",
    youtubeId: "wF_B_aagLfI",
  },
  {
    movie: "Mimi",
    name: "Param Sundari",
    youtubeId: "nfNc0XJdZWk",
  },
  {
    movie: "Raees",
    name: "Laila Main Laila",
    youtubeId: "95I5VaR7GeU",
  },
  {
    movie: "Mubarakan",
    name: "Hawa Hawa",
    youtubeId: "2ll4IA146YI",
  },
  {
    movie: "Student Of The Year 2",
    name: "The Jawaani Song",
    youtubeId: "osBCBg8WAsM",
  },
  {
    movie: "Gori Tere Pyaar Mein",
    name: "Tooh",
    youtubeId: "91kbNw9DZBg",
  },
];
