export const songs = [
  {
    movie: "Veer-Zaara",
    name: "Tere Liye",
    youtubeId: "jo6iAkSoraY",
    startTime: "3",
  },
  {
    movie: "Gangubai Kathiawadi",
    name: "Dholida",
    youtubeId: "uv9Dv6fzg9w",
    startTime: "5",
  },	
  {
    movie: "Dus",
    name: "Dus Bahane Karke Le Gaye Dil",
    youtubeId: "qE3DfF66DNA",
    startTime: "13",
  },	
  {
    movie: "Student Of The Year",
    name: "Radha",
    youtubeId: "52deq20h6Q4",
    startTime: "5",
  },
  {
    movie: "Dil Hai Tumhaara",
    name: "Mohabbat Dil Ka Sakoon",
    youtubeId: "0NtKpBvfRvM",
    startTime: "20",
  },
  {
    movie: "Mohabbatein",
    name: "Pairon Mein Bandhan Hai",
    youtubeId: "bC7RmYYMqTw",
    startTime: "7",
  },
  {
    movie: "Aashiq Banaya Aapne",
    name: "Aap Ki Kashish",
    youtubeId: "jx0qbW_YTCs",
    startTime: "0",
  },
  {
    movie: "Yeh Dillagi",
    name: "Hothon Pe Bas",
    youtubeId: "c-t4nE-KCU8",
    startTime: "24",
  },
  {
    movie: "Kabhi Khushi Kabhie Gham",
    name: "Suraj Hua Maddham",
    youtubeId: "L0zKs8i7Nc8",
    startTime: "70",
  },
  {
    movie: "Main Hoon Na",
    name: "Tumse Milke Dilka Jo Haal",
    youtubeId: "mXkbWKr5ovU",
    startTime: "21",
  },
  {
    movie: "Humpty Sharma Ki Dulhania",
    name: "Lucky Tu Lucky Me",
    youtubeId: "LwvU3DG9qrU",
    startTime: "52",
  },
  {
    movie: "Happy New Year",
    name: "Lovely",
    youtubeId: "HT7g_9eNnYk",
    startTime: "4",
  },
  {
    movie: "Agneepath",
    name: "Chikni Chameli",
    youtubeId: "MQM7CNoAsBI",
    startTime: "29",
  },
  {
    movie: "Stree",
    name: "Milegi Milegi",
    youtubeId: "1xYZeDReUz4",
    startTime: "17",
  },
  {
    movie: "Aarzoo",
    name: "Sajan Sajan Teri Dulhan",
    youtubeId: "vvvDkFN9LUU",
  },
  {
    movie: "Mere Brother Ki Dulhan",
    name: "Do Dhaari Talwaar",
    youtubeId: "m66aEQ3Ssdw",
  },
  {
    movie: "Shamshera",
    name: "Kaale Naina",
    youtubeId: "Ieh-dXsR0OE",
  },
  {
    movie: "Kalank",
    name: "Ghar More Pardesiya",
    youtubeId: "pp8vAFFc5E0",
  },
  {
    movie: "Guru",
    name: "Barso Re",
    youtubeId: "xj_OHHWcPNw",
  },
  {
    movie: "Veer-Zaara",
    name: "Hum To Bhai Jaise Hain",
    youtubeId: "c_L5nSf91zs",
  },
  {
    movie: "Welcome Back",
    name: "Tutti Bole Wedding Di",
    youtubeId: "r2LwEwLiRhc",
  },
  {
    movie: "Housefull 2",
    name: "Right Now Now",
    youtubeId: "m_4lF320DfQ",
  },
  {
    movie: "Dostana",
    name: "Maa Da Laadla",
    youtubeId: "wVCZmXiK-6k",
  },
  {
    movie: "Singh Is Bliing",
    name: "Dil Kare Chu Che",
    youtubeId: "4Lzih-SfYDM",
  },
  {
    movie: "Hum Aapke Hain Koun",
    name: "Maye Ni Maye",
    youtubeId: "Ua5AW2czRAE",
  },
  {
    movie: "Vivah",
    name: "Milan Abhi Aadha Adhura Hai",
    youtubeId: "bv5j1CUTVGM",
  },
  {
    movie: "Fanaa",
    name: "Des Rangila",
    youtubeId: "drlfr5Rtb1o",
  },
  {
    movie: "Kesari",
    name: "Teri Mitti",
    youtubeId: "wF_B_aagLfI",
  },
  {
    movie: "Mimi",
    name: "Param Sundari",
    youtubeId: "nfNc0XJdZWk",
  },
  {
    movie: "Raees",
    name: "Laila Main Laila",
    youtubeId: "95I5VaR7GeU",
  },
  {
    movie: "Mubarakan",
    name: "Hawa Hawa",
    youtubeId: "2ll4IA146YI",
  },
  {
    movie: "Student Of The Year 2",
    name: "The Jawaani Song",
    youtubeId: "osBCBg8WAsM",
  },
  {
    movie: "Gori Tere Pyaar Mein",
    name: "Tooh",
    youtubeId: "91kbNw9DZBg",
  },
];
