export const songs = [
  {
    movie: "Veer-Zaara",
    name: "Tere Liye",
    youtubeId: "jo6iAkSoraY",
    startTime: "3",
  },
  {
    movie: "Gangubai Kathiawadi",
    name: "Dholida",
    youtubeId: "uv9Dv6fzg9w",
    startTime: "5",
  },	
  {
    movie: "Dus",
    name: "Dus Bahane Karke Le Gaye Dil",
    youtubeId: "qE3DfF66DNA",
    startTime: "13",
  },	
  {
    movie: "Student Of The Year",
    name: "Radha",
    youtubeId: "52deq20h6Q4",
    startTime: "5",
  },
  {
    movie: "Dil Hai Tumhaara",
    name: "Mohabbat Dil Ka Sakoon",
    youtubeId: "0NtKpBvfRvM",
    startTime: "20",
  },
  {
    movie: "Mohabbatein",
    name: "Pairon Mein Bandhan Hai",
    youtubeId: "bC7RmYYMqTw",
    startTime: "7",
  },
  {
    movie: "Aashiq Banaya Aapne",
    name: "Aap Ki Kashish",
    youtubeId: "jx0qbW_YTCs",
    startTime: "0",
  },
  {
    movie: "Yeh Dillagi",
    name: "Hothon Pe Bas",
    youtubeId: "c-t4nE-KCU8",
    startTime: "24",
  },
  {
    movie: "Kabhi Khushi Kabhie Gham",
    name: "Suraj Hua Maddham",
    youtubeId: "L0zKs8i7Nc8",
    startTime: "70",
  },
  {
    movie: "Main Hoon Na",
    name: "Tumse Milke Dilka Jo Haal",
    youtubeId: "mXkbWKr5ovU",
    startTime: "21",
  },
  {
    movie: "Humpty Sharma Ki Dulhania",
    name: "Lucky Tu Lucky Me",
    youtubeId: "LwvU3DG9qrU",
    startTime: "52",
  },
  {
    movie: "Happy New Year",
    name: "Lovely",
    youtubeId: "HT7g_9eNnYk",
    startTime: "4",
  },
  {
    movie: "Agneepath",
    name: "Chikni Chameli",
    youtubeId: "MQM7CNoAsBI",
    startTime: "29",
  },
  {
    movie: "Stree",
    name: "Milegi Milegi",
    youtubeId: "1xYZeDReUz4",
    startTime: "17",
  }, 
];
