export const songs = [
  {
    movie: "Yaraana",
    name: "Mera Piya Ghar Aaya",
    youtubeId: "xVViRaALOLM",
    startTime: 0,
  },
  {
    movie: "Partner",
    name: "Soni De Nakhre",
    youtubeId: "GFljvZMZI0U",
    startTime: 0,
  },
  {
    movie: "Dilwale Dulhania Le Jayenge",
    name: "Ruk Ja O Dil Deewane",
    youtubeId: "jBpRItrod-Q",
    startTime: 0,
  },
  {
    movie: "Bachna Ae Haseeno",
    name: "Jogi Mahi",
    youtubeId: "GKyMgyNsRKI",
    startTime: 0,
  },
  {
    movie: "Hum Aapke Hain Koun",
    name: "Didi Tera Devar Deewana",
    youtubeId: "2V56f0xZNqw",
    startTime: 0,
  },
  {
    movie: "Om Shanti Om",
    name: "Deewangi Deewangi",
    youtubeId: "VzLG6OqOcn8",
    startTime: 0,
  },
  {
    movie: "Baar Baar Dekho",
    name: "Kala Chashma",
    youtubeId: "k4yXQkG2s1E",
    startTime: 0,
  },
  {
    movie: "Rab Ne Bana Di Jodi",
    name: "Tujh Mein Rab Dikta Hain",
    youtubeId: "qoq8B8ThgEM",
    startTime: 0,
  },
  {
    movie: "Brahmastra",
    name: "Kesariya",
    youtubeId: "BddP6PYo2gs",
    startTime: 0,
  },
  {
    movie: "Judwaa 2 ",
    name: "Chalti Hai Kya 9 Se 12",
    youtubeId: "E9OFaR2DSOI",
    startTime: 0,
  },
  {
    movie: "Dil Dhadakne Do",
    name: "Gallan Goodiyaan",
    youtubeId: "jCEdTq3j-0U",
    startTime: 1,
  },
  {
    movie: "Namak Halaal",
    name: "Ke Pag Ghunghroo Bandh Meera",
    youtubeId: "SzxeWJjjVd4",
    startTime: 19,
  },
  {
    movie: "Band Baaja Baaraat",
    name: "Ainvayi Ainvayi",
    youtubeId: "pElk1ShPrcE",
    startTime: 0,
  },
  {
    movie: "Hum Dil De Chuke Sanam",
    name: "Chand Chhupa",
    youtubeId: "B3D1cSzigOg",
    startTime: 0,
  },
  {
    movie: "Befikre",
    name: "Nashe Si Chadh Gayi",
    youtubeId: "Wd2B8OAotU8",
    startTime: 0,
  },
  {
    movie: "Gunday",
    name: "Tune Maari Entriyaan",
    youtubeId: "-8SlOkUAW-4",
    startTime: 0,
  },
  {
    movie: "Dabangg 2",
    name: "Fevicol Se",
    youtubeId: "zE7Pwgl6sLA",
    startTime: 0,
  },
  {
    movie: "Ra.One",
    name: "Chammak Challo",
    youtubeId: "lxB-ki-qE64",
    startTime: 0,
  },
  {
    movie: "Singh Is Kinng",
    name: "Jee Karda",
    youtubeId: "40IlftR0R_U",
    startTime: 0,
  },
  {
    movie: "Stree",
    name: "Milegi Milegi",
    youtubeId: "1xYZeDReUz4",
    startTime: 17,
  },
  {
    movie: "Aarzoo",
    name: "Sajan Sajan Teri Dulhan",
    youtubeId: "vvvDkFN9LUU",
    startTime: 0,
  },
  {
    movie: "Mere Brother Ki Dulhan",
    name: "Do Dhaari Talwaar",
    youtubeId: "m66aEQ3Ssdw",
    startTime: 0,
  },
  {
    movie: "Shamshera",
    name: "Kaale Naina",
    youtubeId: "Ieh-dXsR0OE",
    startTime: 0,
  },
  {
    movie: "Kalank",
    name: "Ghar More Pardesiya",
    youtubeId: "pp8vAFFc5E0",
    startTime: 0,
  },
  {
    movie: "Kabhi Khushi Kabhie Gham",
    name: "Kabhi Khushi Kabhie Gham",
    youtubeId: "2wn3RHVpfxE",
    startTime: 1,
  },
  {
    movie: "Veer-Zaara",
    name: "Hum To Bhai Jaise Hain",
    youtubeId: "c_L5nSf91zs",
    startTime: 0,
  },
  {
    movie: "Welcome Back",
    name: "Tutti Bole Wedding Di",
    youtubeId: "r2LwEwLiRhc",
    startTime: 0,
  },
  {
    movie: "Housefull 2",
    name: "Right Now Now",
    youtubeId: "m_4lF320DfQ",
    startTime: 0,
  },
  {
    movie: "Dostana",
    name: "Maa Da Laadla",
    youtubeId: "wVCZmXiK-6k",
    startTime: 1,
  },
  {
    movie: "Singh Is Bliing",
    name: "Dil Kare Chu Che",
    youtubeId: "4Lzih-SfYDM",
    startTime: 0,
  },
  {
    movie: "Hum Aapke Hain Koun",
    name: "Maye Ni Maye",
    youtubeId: "Ua5AW2czRAE",
    startTime: 0,
  },
  {
    movie: "Vivah",
    name: "Milan Abhi Aadha Adhura Hai",
    youtubeId: "bv5j1CUTVGM",
    startTime: 0,
  },
  {
    movie: "Fanaa",
    name: "Des Rangila",
    youtubeId: "drlfr5Rtb1o",
    startTime: 0,
  },
  {
    movie: "Kesari",
    name: "Teri Mitti",
    youtubeId: "wF_B_aagLfI",
    startTime: 0,
  },
  {
    movie: "Mimi",
    name: "Param Sundari",
    youtubeId: "nfNc0XJdZWk",
    startTime: 0,
  },
  {
    movie: "Raees",
    name: "Laila Main Laila",
    youtubeId: "95I5VaR7GeU",
    startTime: 0,
  },
  {
    movie: "Mubarakan",
    name: "Hawa Hawa",
    youtubeId: "2ll4IA146YI",
    startTime: 0,
  },
  {
    movie: "Student Of The Year 2",
    name: "The Jawaani Song",
    youtubeId: "osBCBg8WAsM",
    startTime: 0,
  },
  {
    movie: "Gori Tere Pyaar Mein",
    name: "Tooh",
    youtubeId: "91kbNw9DZBg",
    startTime: 0,
  },
  {
    movie: "Veer-Zaara",
    name: "Tere Liye",
    youtubeId: "jo6iAkSoraY",
    startTime: 3,
  },
  {
    movie: "Gangubai Kathiawadi",
    name: "Dholida",
    youtubeId: "uv9Dv6fzg9w",
    startTime: 5,
  },
  {
    movie: "Dus",
    name: "Dus Bahane Karke Le Gaye Dil",
    youtubeId: "qE3DfF66DNA",
    startTime: 13,
  },
  {
    movie: "Student Of The Year",
    name: "Radha",
    youtubeId: "52deq20h6Q4",
    startTime: 5,
  },
  {
    movie: "Dil Hai Tumhaara",
    name: "Mohabbat Dil Ka Sakoon",
    youtubeId: "0NtKpBvfRvM",
    startTime: 20,
  },
  {
    movie: "Mohabbatein",
    name: "Pairon Mein Bandhan Hai",
    youtubeId: "bC7RmYYMqTw",
    startTime: 7,
  },
  {
    movie: "Aashiq Banaya Aapne",
    name: "Aap Ki Kashish",
    youtubeId: "jx0qbW_YTCs",
    startTime: 0,
  },
  {
    movie: "Yeh Dillagi",
    name: "Hothon Pe Bas",
    youtubeId: "c-t4nE-KCU8",
    startTime: 24,
  },
  {
    movie: "Kabhi Khushi Kabhie Gham",
    name: "Suraj Hua Maddham",
    youtubeId: "L0zKs8i7Nc8",
    startTime: 70,
  },
  {
    movie: "Main Hoon Na",
    name: "Tumse Milke Dilka Jo Haal",
    youtubeId: "mXkbWKr5ovU",
    startTime: 21,
  },
  {
    movie: "Humpty Sharma Ki Dulhania",
    name: "Lucky Tu Lucky Me",
    youtubeId: "LwvU3DG9qrU",
    startTime: 52,
  },
  {
    movie: "Happy New Year",
    name: "Lovely",
    youtubeId: "HT7g_9eNnYk",
    startTime: 4,
  },
  {
    movie: "Agneepath",
    name: "Chikni Chameli",
    youtubeId: "MQM7CNoAsBI",
    startTime: 29,
  },
];
