export const songs = [
  {
    movie: "Yaraana",
    name: "Mera Piya Ghar Aaya",
    youtubeId: "xVViRaALOLM",
    startTime: 0,
  },
  {
    movie: "Partner",
    name: "Soni De Nakhre",
    youtubeId: "GFljvZMZI0U",
    startTime: 0,
  },
  {
    movie: "Tashan",
    name: "Falak Tak",
    youtubeId: "vr8RaNuWjWc",
    startTime: 0,
  },
  {
    movie: "Dilwale Dulhania Le Jayenge",
    name: "Ruk Ja O Dil Deewane",
    youtubeId: "jBpRItrod-Q",
    startTime: 0,
  },
  {
    movie: "Bachna Ae Haseeno",
    name: "Jogi Mahi",
    youtubeId: "GKyMgyNsRKI",
    startTime: 0,
  },
  {
    movie: "Hum Aapke Hain Koun",
    name: "Didi Tera Devar Deewana",
    youtubeId: "2V56f0xZNqw",
    startTime: 0,
  },
  {
    movie: "Om Shanti Om",
    name: "Deewangi Deewangi",
    youtubeId: "VzLG6OqOcn8",
    startTime: 0,
  },
  {
    movie: "Rab Ne Bana Di Jodi",
    name: "Tujh Mein Rab Dikta Hain",
    youtubeId: "qoq8B8ThgEM",
    startTime: 0,
  },
  {
    movie: "Brahmastra",
    name: "Kesariya",
    youtubeId: "BddP6PYo2gs",
    startTime: 0,
  },
  {
    movie: "Judwaa 2 ",
    name: "Chalti Hai Kya 9 Se 12",
    youtubeId: "E9OFaR2DSOI",
    startTime: 0,
  },
  {
    movie: "Dil Dhadakne Do",
    name: "Gallan Goodiyaan",
    youtubeId: "jCEdTq3j-0U",
    startTime: 0,
  },
  {
    movie: "Band Baaja Baaraat",
    name: "Ainvayi Ainvayi",
    youtubeId: "pElk1ShPrcE",
    startTime: 0,
  },
  {
    movie: "Fan",
    name: "Jabra Fan",
    youtubeId: "d4_szl5EEww",
    startTime: 0,
  },
  {
    movie: "Befikre",
    name: "Nashe Si Chadh Gayi",
    youtubeId: "Wd2B8OAotU8",
    startTime: 0,
  },
  {
    movie: "Gunday",
    name: "Tune Maari Entriyaan",
    youtubeId: "-8SlOkUAW-4",
    startTime: 0,
  },
  {
    movie: "Dabangg 2",
    name: "Fevicol Se",
    youtubeId: "zE7Pwgl6sLA",
    startTime: 0,
  },
  {
    movie: "Ra.One",
    name: "Chammak Challo",
    youtubeId: "lxB-ki-qE64",
    startTime: 0,
  },
  {
    movie: "Singh Is Kinng",
    name: "Jee Karda",
    youtubeId: "40IlftR0R_U",
    startTime: 0,
  },
  {
    movie: "Baar Baar Dekho",
    name: "Kala Chashma",
    youtubeId: "k4yXQkG2s1E",
    startTime: 0,
  },
];
